name: estacio-m2-n2
services:
  app:
    build:
      context: .
    command: -p $PORT
    container_name: livros-next
    hostname: estacio.next.livraria
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $PORT:$PORT
    networks: [estacio-net]
networks:
  estacio-net:
    external: true 
    name: estacio-net